---
# API v1 description. See https://spec.openapis.org/oas/v3.1.0 for specification.
# Edit using https://editor.swagger.io/.

permalink: /docs/api/v1/openapi.yml
layout: null
---
openapi: 3.0.3

info:
  title: endoflife API
  version: "1.0.0-b1"
  license:
    name: MIT License
    url: 'https://github.com/endoflife-date/endoflife.date/blob/master/LICENSE'
  description: >-
    endoflife.date documents EOL dates and support lifecycles for various products.
    The endoflife API allows users to discover and query for those products.


    Some useful links:

    - [The endoflife.date website](https://endoflife.date/)

    - [The endoflife.date repository](https://github.com/endoflife-date/endoflife.date)

    - [The endoflife.date issue tracker](https://github.com/endoflife-date/endoflife.date/issues/)

    - [The source API definition](https://github.com/endoflife-date/endoflife.date/blob/master/assets/openapi.yml)

# Replace with your preview URL (such as https://deploy-preview-2080--endoflife-date.netlify.app/api/v1).
servers:
  - url: {{ site.url }}/api/v1

paths:
  /:
    get:
      summary: List the main endoflife.date API endpoints.
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UriListResponse'

  /products:
    get:
      summary: >
        List all the products referenced on endoflife.date.
        Only a subset of each product's data is returned by this endpoint.
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListResponse'

  /products/{product}/:
    get:
      summary: >
        Get the given product data.
        This endpoint is returning all endoflife.date knows about the product, including release
        cycles data.
      parameters:
        - name: product
          in: path
          description: 'The name of the product.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'

  /products/{product}/cycles/{cycle}:
    get:
      summary: Get the given product release cycle data.
      parameters:
        - name: product
          in: path
          description: 'The name of the product.'
          required: true
          schema:
            type: string
        - name: cycle
          in: path
          description: 'The name of the cycle.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCycleResponse'

  /products/{product}/cycles/latest/:
    get:
      summary: Get the latest release cycle data for the given product.
      parameters:
        - name: product
          in: path
          description: 'The name of the product.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCycleResponse'

  /categories:
    get:
      summary: List all endoflife.date categories.
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UriListResponse'

  /categories/{category}:
    get:
      summary: >
        List all the products referenced on endoflife.date for the given category.
        Only a subset of each product's data is returned by this endpoint.
      parameters:
        - name: category
          in: path
          description: 'The name of the category.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListResponse'

  /tags:
    get:
      summary: List all endoflife.date tags.
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UriListResponse'

  /tags/{tag}:
    get:
      summary: >
        List all the products referenced on endoflife.date for the given tag.
        Only a subset of each product's data is returned by this endpoint.
      parameters:
        - name: tag
          in: path
          description: 'The name of the tag.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListResponse'

# Responses must be at the end of the list, contain a schema_version property and be suffixed with
# 'Response' to facilitate maintenance and reading.
components:
  schemas:
    Uri:
      type: object
      properties:
        name:
          type: string
          description: Name of the URI
          example: tags
        uri:
          type: string
          format: uri
          description: URI
          example: {{ site.url }}/tags/

    Identifier:
      type: object
      properties:
        name:
          type: type
          description: Type of the identifier (types as of 2023-03 are repology, purl and cpe)
          example: purl
        id:
          type: string
          description: Identifier
          example: cpe:/o:almalinux:almalinux

    ProductVersion:
      type: object
      properties:
        name:
          type: string
          description: Name of the version.
          example: "11.6"
        date:
          type: string
          format: date
          description: Release date.
          example: "2022-12-17"
        link:
          type: string
          format: uri
          description: Link to the changelog or release notes.
          example: https://www.debian.org/News/2022/2022091002

    ProductCycle:
      type: object
      properties:
        name:
          type: string
          description: Name of the product cycle.
          example: "11"
        codename:
          type: string
          nullable: true
          description: Name of the product cycle.
          example: Bullseye
        label:
          type: string
          description: Label of the product cycle.
          example: 11 (Bullseye) (Upcoming LTS)
        date:
          type: string
          format: date
          description: Date of the first version of the cycle.
          example: "2021-08-14"
        support:
          oneOf:
            - type: string
              format: date
            - type: boolean
          nullable: true
          description: End of active support date, or true / false to indicate whether or not the product cycle is still supported.
          example: "2021-08-14"
        lts:
          oneOf:
            - type: string
              format: date
            - type: boolean
          nullable: true
          description: Start date of the LTS phase, or true / false to indicate whether or not the product cycle is LTS.
          example: "2021-08-14"
        eol:
          oneOf:
            - type: string
              format: date
            - type: boolean
          description: End of life date, or true / false to indicate whether or not the product cycle is EOL.
          example: "2026-08-15"
        discontinued:
          oneOf:
            - type: string
              format: date
            - type: boolean
          nullable: true
          description: Discontinued date, or true / false to indicate whether or not the product cycle is discontinued (mainly used for hardware).
          example: "2026-08-15"
        extendedSupport:
          oneOf:
            - type: string
              format: date
            - type: boolean
          nullable: true
          description: End of extended support date, or true / false to indicate whether or not the product cycle is still in the extended support phase.
          example: "2029-08-15"
        latest:
          type: object
          $ref: '#/components/schemas/ProductVersion'

    ProductSummary:
      type: object
      properties:
        name:
          type: string
          description: Name of the product
          example: debian
        label:
          type: string
          description: Label of the product
          example: Debian GNU/Linux
        category:
          type: string
          description: Category of the product
          example: os
        tags:
          type: array
          description: Tags associated to the product
          items:
            type: string
        identifiers:
          type: array
          description: Known identifiers (purl, repology, cpe...) associated to the product
          items:
            $ref: '#/components/schemas/Identifier'
        uri:
          type: string
          format: uri
          description: Link to the full product details
          example: {{ site.url }}/api/v1/products/debian/

    ProductDetails:
      type: object
      properties:
        name:
          type: string
          description: Name of the product
          example: debian
        label:
          type: string
          description: Label of the product
          example: Debian GNU/Linux
        category:
          type: string
          description: Category of the product
          example: os
        tags:
          type: array
          description: Tags associated to the product
          items:
            type: string
        identifiers:
          type: array
          description: Known identifiers (purl, repology, cpe...) associated to the product
          items:
            $ref: '#/components/schemas/Identifier'
        # Additional properties (compared to ProductSummary)
        links:
          type: object
          description: Product links.
          properties:
            icon:
              type: string
              format: uri
              nullable: true
              description: Link to the product icon (on https://simpleicons.org/).
              example: https://simpleicons.org/icons/debian.svg
            html:
              type: string
              format: uri
              description: Link to the product page on endoflife.date.
              example: https://endoflife.date/debian
            releasePolicy:
              type: string
              format: uri
              nullable: true
              description: Link to the product release policy.
              example: https://wiki.debian.org/DebianReleases
        versionCommand:
          type: string
          description: Command that can be used to check the current product version.
          example: cat /etc/os-release
        cycles:
          type: array
          description: Product release cycles.
          items:
            $ref: '#/components/schemas/ProductCycle'

    UriListResponse:
      type: object
      properties:
        schema_version:
          type: string
          description: Version of this schema.
          example: 1.0.0
        result:
          type: array
          items:
            $ref: '#/components/schemas/Uri'

    ProductListResponse:
      type: object
      properties:
        schema_version:
          type: string
          description: Version of this schema.
          example: 1.0.0
        total:
          type: integer
          format: int32
          description: Number of products in the list.
          example: 1
        result:
          type: array
          items:
            $ref: '#/components/schemas/ProductSummary'

    ProductCycleResponse:
      type: object
      properties:
        schema_version:
          type: string
          description: Version of this schema.
          example: 1.0.0
        result:
          $ref: '#/components/schemas/ProductCycle'

    ProductResponse:
      type: object
      properties:
        schema_version:
          type: string
          description: Version of this schema.
          example: 1.0.0
        last_modified:
          type: string
          format: date-time
          description: The time this product was last modified.
          example: 2023-03-01T14:05:52+01:00
        auto:
          type: boolean
          description: Whether or not product versions are automatically updated.
          example: true
        result:
          $ref: '#/components/schemas/ProductDetails'
